ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "latitude"     DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "longitude"    DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "radiusMeters" INTEGER NOT NULL DEFAULT 200;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "updatedAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Branch" ALTER COLUMN "latitude"  DROP DEFAULT;
ALTER TABLE "Branch" ALTER COLUMN "longitude" DROP DEFAULT;

ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "latitude"       DOUBLE PRECISION;
ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "longitude"      DOUBLE PRECISION;
ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "distanceMeters" DOUBLE PRECISION;

ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "branchId" INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Employee_branchId_fkey'
  ) THEN
    ALTER TABLE "Employee"
      ADD CONSTRAINT "Employee_branchId_fkey"
      FOREIGN KEY ("branchId") REFERENCES "Branch"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;